---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tkc-dev-user
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./.weave-gitops/clusters/tkc-dev/user
  prune: true
  sourceRef:
    kind: GitRepository
    name: wego-github-gitops-config

